export const tagRecommendations: Record<string, string> = {
  'Intensa': 'Personas que buscan una obra con momentos intensos que hagan retumbar el corazón.',
  'Personajes': 'Personas que buscan una obra que desarrolla múltiples personajes interesantes.',
  'No casual': 'Personas que no buscan una obra casual, sino una obra que demanda disposición y atención para ser apreciada correctamente.',
  'Comedia': 'Personas que buscan una comedia de las buenas.',
  'Peak': 'Personas que buscan una obra que tenga momentos qls insanos de buenos.',
  'Chilena': 'Personas que quieren una obra marcadamente chilena.',
  'Guión 🔥': 'Personas que buscan una obra con diálogos potentes, hechos con cuidado.',
  'Agridulce': 'Personas que buscan una obra que, como la vida misma, no es completamente feliz ni completamente triste.',
  'Tragedia ágil': 'Personas que buscan una tragedia que se narra como si fuera una comedia.',
  'Ligera': 'Personas que buscan una obra ligera, que no pese mucho en el ánimo.',
  'Densa': 'Personas que no temen a una obra que toque temas y situaciones duras.',
  'Final feliz': 'Personas que buscan una obra con un final feliz que no los deje por el suelo (Se sorprenderían de cuántas obras no terminan bien).',
  'Realista': 'Personas que buscan una obra que se sienta realista y creíble.',
  'Poética': 'Personas que buscan una obra que sacrifica realismo por diálogos más poéticos y simbólicos.',
  'Surreal': 'Personas que buscan una obra que exagera la realidad para mostrarla desde otro ángulo.',
};
